### ISSUE TITLE
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

### ISSUE THREAD

**Issue by Ahsan686** [RevolveAI/BenchmarkMyAI#2]
following error occured while running 'python runall.py'.

Traceback (most recent call last):
  File "runall.py", line 64, in <module>
    runAll()
  File "runall.py", line 26, in runAll
    model_names = rbm.models.models_names()
  File "/home/ahsan/Downloads/REVOLVEAI/benchmarking/BenchmarkMyAI/rbm/utils/plugins.py", line 30, in names
    _import_all(package)
  File "/home/ahsan/Downloads/REVOLVEAI/benchmarking/BenchmarkMyAI/rbm/utils/plugins.py", line 67, in _import_all
    _import(package, plugin)
  File "/home/ahsan/Downloads/REVOLVEAI/benchmarking/BenchmarkMyAI/rbm/utils/plugins.py", line 50, in _import
    importlib.import_module(f"{package}.{plugin}")
  File "/opt/miniconda3/envs/benchmark/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ahsan/Downloads/REVOLVEAI/benchmarking/BenchmarkMyAI/rbm/models/cv/object-detection/spinenet_backbone.py", line 5, in <module>
    from official.vision.beta.modeling.backbones.spinenet import SpineNet as spineNet
  File "/opt/miniconda3/envs/benchmark/lib/python3.8/site-packages/official/vision/beta/__init__.py", line 19, in <module>
    from official.vision.beta import tasks
  File "/opt/miniconda3/envs/benchmark/lib/python3.8/site-packages/official/vision/beta/tasks/__init__.py", line 19, in <module>
    from official.vision.beta.tasks import maskrcnn
  File "/opt/miniconda3/envs/benchmark/lib/python3.8/site-packages/official/vision/beta/tasks/maskrcnn.py", line 28, in <module>
    from official.vision.beta.evaluation import coco_evaluator
  File "/opt/miniconda3/envs/benchmark/lib/python3.8/site-packages/official/vision/beta/evaluation/coco_evaluator.py", line 34, in <module>
    from pycocotools import cocoeval
  File "/opt/miniconda3/envs/benchmark/lib/python3.8/site-packages/pycocotools/cocoeval.py", line 7, in <module>
    from . import mask as maskUtils
  File "/opt/miniconda3/envs/benchmark/lib/python3.8/site-packages/pycocotools/mask.py", line 3, in <module>
    import pycocotools._mask as _mask
  File "pycocotools/_mask.pyx", line 1, in init pycocotools._mask
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject

**Comment by Ahsan686** [comment]
to reproduce this error, create conda environment with python 3.8 and run 'python runall.py'

**Comment by Ahsan686** [comment]
uninstalling numpy and then reinstalling numpy==1.21.2 solves this problem
